### ISSUE TITLE
performReverseAuthForAccount:withAndler: sometimes fails without any error and responseData not nil

### ISSUE THREAD

**Issue by oiledCode** [seancook/TWReverseAuthExample#10]
I'm experiencing something "weird" sometimes the reverse auth fails and what I receive back from performReverseAuthForAccount:withAndler: is the following xml :
![image](https://f.cloud.github.com/assets/580402/1103080/f7e07e04-1884-11e3-85d1-9e4a1b8acc56.png)
To workAround this for now I check if responseData has the "right" format but looks like a weak solution.
Do you have any idea of what is going on?

**Comment by seancook** [comment]
Closing after 2 years.
