### ISSUE TITLE
Error: Timestamp out of bounds 

### ISSUE THREAD

**Issue by theXdeveloper** [seancook/TWReverseAuthExample#14]
After I added my twitter key and secret, I run the project but I got the following error:
Reverse Auth process returned: <?xml version="1.0" encoding="UTF-8"?>
<hash>
  <error>Timestamp out of bounds</error>
  <request>/oauth/access_token</request>
</hash>

I'm using iPhone 4s with iOS 7
Please check attached image 
![photo](https://f.cloud.github.com/assets/4497161/2267847/c7577410-9ebf-11e3-9d3d-26a0a2398379.png)

**Comment by ARGAMX** [comment]
The same trouble with device iOS 7. Working on simulator with iOS 8.
