### ISSUE TITLE
Consumer secret in the app?

### ISSUE THREAD

**Issue by brightbits** [seancook/TWReverseAuthExample#18]
Doesn't this mean that anyone with a jailbroken phone, a few hours and the right tools can get the consumer token and secret?

Sounds like a bad idea to me..

**Comment by seancook** [comment]
Apologies for not responding to this issue sooner.  For posterity:

Yes, any OAuth1.0a application that stores its consumer secret in the client is "crackable." Unfortunately, it has become all too common for mobile Twitter apps to do just that. The correct, production-ready solution would be to do the token exchange on a server, and have the client talk to the server. 

I'll add an example of this to the project. Thanks for raising it here.

-Sean
