### ISSUE TITLE
"NSURLErrorDomain error -1012" on iOS7 with iPhone 4

### ISSUE THREAD

**Issue by psi-gh** [seancook/TWReverseAuthExample#20]
I get this error after step 1. In description said that 'Operation couldn't be completed'. It appears only on device, in simulator it works for both iOS 7 and iOS 8. And it also works on device with iOS 8. What can cause this problem?

**Comment by seancook** [comment]
For posterity: This issue can occur after a restore of a device, most commonly post-upgrade (e.g. iOS7 -> iOS8) if you do not store your backups as encrypted. There are some other causes, but this is the one that I've seen the most.
