### ISSUE TITLE
Remove Action Sheet

### ISSUE THREAD

**Issue by kylebegeman** [seancook/TWReverseAuthExample#7]
I have been attempting to use this project, but use it without the action sheet. I would like the app to automatically check at launch if the user is signed in to twitter, and then perform the swap if so, otherwise alert the user. 

Any idea on what it would take to do this? Thanks a lot!

**Comment by seancook** [comment]
Closing after 2 years. Sorry for not responding sooner-- I'm assuming you figured it out :)
